# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import inokufu_encoder_client
from inokufu_encoder_client.api.default_api import DefaultApi  # noqa: E501
from inokufu_encoder_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = inokufu_encoder_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_encode_encode_post(self):
        """Test case for encode_encode_post

        Encode  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
