# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import inokufu_encoder_client
from inokufu_encoder_client.models.lang_enum import LangEnum  # noqa: E501
from inokufu_encoder_client.rest import ApiException

class TestLangEnum(unittest.TestCase):
    """LangEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLangEnum(self):
        """Test LangEnum"""
        # inst = LangEnum()

if __name__ == '__main__':
    unittest.main()
