# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import inokufu_encoder_client
from inokufu_encoder_client.models.response_model import ResponseModel  # noqa: E501
from inokufu_encoder_client.rest import ApiException

class TestResponseModel(unittest.TestCase):
    """ResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseModel`
        """
        model = inokufu_encoder_client.models.response_model.ResponseModel()  # noqa: E501
        if include_optional :
            return ResponseModel(
                index = '0', 
                query = 'apprendre le python', 
                vector = [0.1,0.2,0.3]
            )
        else :
            return ResponseModel(
                index = '0',
                query = 'apprendre le python',
        )
        """

    def testResponseModel(self):
        """Test ResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
