# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from inokufu_encoder_client.models.http_validation_error import HTTPValidationError
from inokufu_encoder_client.models.lang_enum import LangEnum
from inokufu_encoder_client.models.location_inner import LocationInner
from inokufu_encoder_client.models.query_model import QueryModel
from inokufu_encoder_client.models.response_model import ResponseModel
from inokufu_encoder_client.models.validation_error import ValidationError
