# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class LangEnum(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    FR = 'fr'
    EN = 'en'

    @classmethod
    def from_json(cls, json_str: str) -> LangEnum:
        """Create an instance of LangEnum from a JSON string"""
        return LangEnum(json.loads(json_str))


